USE [master]
RESTORE DATABASE [IncentivesUK] FROM  DISK = N'D:\Martin1\IncentivesUK_backup_2022_12_20_220000_6180708.bak' WITH  FILE = 1,  MOVE N'distributor1' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\IncentivesUK.mdf',  MOVE N'distributor1_log' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\IncentivesUK_log.ldf',  NOUNLOAD,  STATS = 5
RESTORE DATABASE [InformPrintedSolutions] FROM  DISK = N'D:\Martin1\InformPrintedSolutions_backup_2022_12_20_220000_6180708.bak' WITH  FILE = 1,  MOVE N'distributor1' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\InformPrintedSolutions.mdf',  MOVE N'distributor1_log' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\InformPrintedSolutions_log.ldf',  NOUNLOAD,  STATS = 5
RESTORE DATABASE [InitialIncentivesLimited] FROM  DISK = N'D:\Martin1\InitialIncentivesLimited_backup_2022_12_20_220000_6336977.bak' WITH  FILE = 1,  MOVE N'distributor1' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\InitialIncentivesLimited.mdf',  MOVE N'distributor1_log' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\InitialIncentivesLimited_log.ldf',  NOUNLOAD,  STATS = 5
RESTORE DATABASE [InitialIncentives] FROM  DISK = N'D:\Martin1\InitialIncentives_backup_2022_12_20_220000_6336977.bak' WITH  FILE = 1,  MOVE N'distributor1' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\InitialIncentives.mdf',  MOVE N'distributor1_log' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\InitialIncentives_log.ldf',  NOUNLOAD,  STATS = 5
RESTORE DATABASE [IVCPrintClubLimited] FROM  DISK = N'D:\Martin1\IVCPrintClubLimited_backup_2022_12_20_220000_6336977.bak' WITH  FILE = 1,  MOVE N'distributor1' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\IVCPrintClubLimited.mdf',  MOVE N'distributor1_log' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\IVCPrintClubLimited_log.ldf',  NOUNLOAD,  STATS = 5
RESTORE DATABASE [JNIInternational] FROM  DISK = N'D:\Martin1\JNIInternational_backup_2022_12_20_220000_6336977.bak' WITH  FILE = 1,  MOVE N'distributor1' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\JNIInternational.mdf',  MOVE N'distributor1_log' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\JNIInternational_log.ldf',  NOUNLOAD,  STATS = 5
RESTORE DATABASE [JWAPromotionalProducts] FROM  DISK = N'D:\Martin1\JWAPromotionalProducts_backup_2022_12_20_220000_6336977.bak' WITH  FILE = 1,  MOVE N'distributor1' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\JWAPromotionalProducts.mdf',  MOVE N'distributor1_log' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\JWAPromotionalProducts_log.ldf',  NOUNLOAD,  STATS = 5
RESTORE DATABASE [JWA] FROM  DISK = N'D:\Martin1\JWA_backup_2022_12_20_220000_6336977.bak' WITH  FILE = 1,  MOVE N'distributor1' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\JWA.mdf',  MOVE N'distributor1_log' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\JWA_log.ldf',  NOUNLOAD,  STATS = 5
RESTORE DATABASE [MacmillanandCompany] FROM  DISK = N'D:\Martin1\MacmillanandCompany_backup_2022_12_20_220000_6336977.bak' WITH  FILE = 1,  MOVE N'distributor1' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\MacmillanandCompany.mdf',  MOVE N'distributor1_log' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\MacmillanandCompany_log.ldf',  NOUNLOAD,  STATS = 5
RESTORE DATABASE [ManicMerchandise] FROM  DISK = N'D:\Martin1\ManicMerchandise_backup_2022_12_20_220000_6493237.bak' WITH  FILE = 1,  MOVE N'distributor1' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\ManicMerchandise.mdf',  MOVE N'distributor1_log' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\ManicMerchandise_log.ldf',  NOUNLOAD,  STATS = 5
RESTORE DATABASE [MarketingMerchandise] FROM  DISK = N'D:\Martin1\MarketingMerchandise_backup_2022_12_20_220000_6493237.bak' WITH  FILE = 1,  MOVE N'distributor1' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\MarketingMerchandise.mdf',  MOVE N'distributor1_log' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\MarketingMerchandise_log.ldf',  NOUNLOAD,  STATS = 5
RESTORE DATABASE [master] FROM  DISK = N'D:\Martin1\master_backup_2022_12_20_220000_6493237.bak' WITH  FILE = 1,  MOVE N'distributor1' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\master.mdf',  MOVE N'distributor1_log' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\master_log.ldf',  NOUNLOAD,  STATS = 5
RESTORE DATABASE [MerchandiseBrandingLimited] FROM  DISK = N'D:\Martin1\MerchandiseBrandingLimited_backup_2022_12_20_220000_6493237.bak' WITH  FILE = 1,  MOVE N'distributor1' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\MerchandiseBrandingLimited.mdf',  MOVE N'distributor1_log' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\MerchandiseBrandingLimited_log.ldf',  NOUNLOAD,  STATS = 5
RESTORE DATABASE [MindvisionMediaLtd] FROM  DISK = N'D:\Martin1\MindvisionMediaLtd_backup_2022_12_20_220000_6493237.bak' WITH  FILE = 1,  MOVE N'distributor1' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\MindvisionMediaLtd.mdf',  MOVE N'distributor1_log' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\MindvisionMediaLtd_log.ldf',  NOUNLOAD,  STATS = 5
RESTORE DATABASE [model] FROM  DISK = N'D:\Martin1\model_backup_2022_12_20_220000_6493237.bak' WITH  FILE = 1,  MOVE N'distributor1' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\model.mdf',  MOVE N'distributor1_log' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\model_log.ldf',  NOUNLOAD,  STATS = 5
RESTORE DATABASE [MonarchPromotions] FROM  DISK = N'D:\Martin1\MonarchPromotions_backup_2022_12_20_220000_6493237.bak' WITH  FILE = 1,  MOVE N'distributor1' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\MonarchPromotions.mdf',  MOVE N'distributor1_log' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\MonarchPromotions_log.ldf',  NOUNLOAD,  STATS = 5
RESTORE DATABASE [NeedSolutionsLimited] FROM  DISK = N'D:\Martin1\NeedSolutionsLimited_backup_2022_12_20_220000_6652582.bak' WITH  FILE = 1,  MOVE N'distributor1' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\NeedSolutionsLimited.mdf',  MOVE N'distributor1_log' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\NeedSolutionsLimited_log.ldf',  NOUNLOAD,  STATS = 5
RESTORE DATABASE [OutstandingBranding] FROM  DISK = N'D:\Martin1\OutstandingBranding_backup_2022_12_20_220000_6669340.bak' WITH  FILE = 1,  MOVE N'distributor1' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\OutstandingBranding.mdf',  MOVE N'distributor1_log' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\OutstandingBranding_log.ldf',  NOUNLOAD,  STATS = 5
RESTORE DATABASE [PavilionGroup] FROM  DISK = N'D:\Martin1\PavilionGroup_backup_2022_12_20_220000_6690079.bak' WITH  FILE = 1,  MOVE N'distributor1' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\PavilionGroup.mdf',  MOVE N'distributor1_log' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\PavilionGroup_log.ldf',  NOUNLOAD,  STATS = 5
RESTORE DATABASE [PavillionGroup] FROM  DISK = N'D:\Martin1\PavillionGroup_backup_2022_12_20_220000_6690079.bak' WITH  FILE = 1,  MOVE N'distributor1' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\PavillionGroup.mdf',  MOVE N'distributor1_log' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\PavillionGroup_log.ldf',  NOUNLOAD,  STATS = 5
RESTORE DATABASE [PGBranding] FROM  DISK = N'D:\Martin1\PGBranding_backup_2022_12_20_220000_6690079.bak' WITH  FILE = 1,  MOVE N'distributor1' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\PGBranding.mdf',  MOVE N'distributor1_log' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\PGBranding_log.ldf',  NOUNLOAD,  STATS = 5
RESTORE DATABASE [PhotoandDesign] FROM  DISK = N'D:\Martin1\PhotoandDesign_backup_2022_12_20_220000_6690079.bak' WITH  FILE = 1,  MOVE N'distributor1' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\PhotoandDesign.mdf',  MOVE N'distributor1_log' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\PhotoandDesign_log.ldf',  NOUNLOAD,  STATS = 5
RESTORE DATABASE [PinfoldPromotions] FROM  DISK = N'D:\Martin1\PinfoldPromotions_backup_2022_12_20_220000_6690079.bak' WITH  FILE = 1,  MOVE N'distributor1' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\PinfoldPromotions.mdf',  MOVE N'distributor1_log' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\PinfoldPromotions_log.ldf',  NOUNLOAD,  STATS = 5
RESTORE DATABASE [PPIncentives] FROM  DISK = N'D:\Martin1\PPIncentives_backup_2022_12_20_220000_6690079.bak' WITH  FILE = 1,  MOVE N'distributor1' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\PPIncentives.mdf',  MOVE N'distributor1_log' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\PPIncentives_log.ldf',  NOUNLOAD,  STATS = 5
RESTORE DATABASE [PressplusLimited_OLD] FROM  DISK = N'D:\Martin1\PressplusLimited_OLD_backup_2022_12_20_220000_6690079.bak' WITH  FILE = 1,  MOVE N'distributor1' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\PressplusLimited_OLD.mdf',  MOVE N'distributor1_log' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\PressplusLimited_OLD_log.ldf',  NOUNLOAD,  STATS = 5
RESTORE DATABASE [ProductNetwork] FROM  DISK = N'D:\Martin1\ProductNetwork_backup_2022_12_20_220000_6690079.bak' WITH  FILE = 1,  MOVE N'distributor1' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\ProductNetwork.mdf',  MOVE N'distributor1_log' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\ProductNetwork_log.ldf',  NOUNLOAD,  STATS = 5
RESTORE DATABASE [PromoMerchUKLtd] FROM  DISK = N'D:\Martin1\PromoMerchUKLtd_backup_2022_12_20_220000_6846369.bak' WITH  FILE = 1,  MOVE N'distributor1' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\PromoMerchUKLtd.mdf',  MOVE N'distributor1_log' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\PromoMerchUKLtd_log.ldf',  NOUNLOAD,  STATS = 5
RESTORE DATABASE [QuestBranding] FROM  DISK = N'D:\Martin1\QuestBranding_backup_2022_12_20_220000_6846369.bak' WITH  FILE = 1,  MOVE N'distributor1' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\QuestBranding.mdf',  MOVE N'distributor1_log' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\QuestBranding_log.ldf',  NOUNLOAD,  STATS = 5
RESTORE DATABASE [ReportServerTempDB] FROM  DISK = N'D:\Martin1\ReportServerTempDB_backup_2022_12_20_220000_6846369.bak' WITH  FILE = 1,  MOVE N'distributor1' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\ReportServerTempDB.mdf',  MOVE N'distributor1_log' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\ReportServerTempDB_log.ldf',  NOUNLOAD,  STATS = 5
RESTORE DATABASE [ReportServer] FROM  DISK = N'D:\Martin1\ReportServer_backup_2022_12_20_220000_6846369.bak' WITH  FILE = 1,  MOVE N'distributor1' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\ReportServer.mdf',  MOVE N'distributor1_log' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\ReportServer_log.ldf',  NOUNLOAD,  STATS = 5
RESTORE DATABASE [RocketCharities] FROM  DISK = N'D:\Martin1\RocketCharities_backup_2022_12_20_220000_6846369.bak' WITH  FILE = 1,  MOVE N'distributor1' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\RocketCharities.mdf',  MOVE N'distributor1_log' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\RocketCharities_log.ldf',  NOUNLOAD,  STATS = 5
RESTORE DATABASE [SETGroup] FROM  DISK = N'D:\Martin1\SETGroup_backup_2022_12_20_220000_6846369.bak' WITH  FILE = 1,  MOVE N'distributor1' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\SETGroup.mdf',  MOVE N'distributor1_log' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\SETGroup_log.ldf',  NOUNLOAD,  STATS = 5
RESTORE DATABASE [SourcingUK] FROM  DISK = N'D:\Martin1\SourcingUK_backup_2022_12_20_220000_6846369.bak' WITH  FILE = 1,  MOVE N'distributor1' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\SourcingUK.mdf',  MOVE N'distributor1_log' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\SourcingUK_log.ldf',  NOUNLOAD,  STATS = 5
RESTORE DATABASE [SportVisionLimited] FROM  DISK = N'D:\Martin1\SportVisionLimited_backup_2022_12_20_220000_7002629.bak' WITH  FILE = 1,  MOVE N'distributor1' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\SportVisionLimited.mdf',  MOVE N'distributor1_log' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\SportVisionLimited_log.ldf',  NOUNLOAD,  STATS = 5
RESTORE DATABASE [StaySourced] FROM  DISK = N'D:\Martin1\StaySourced_backup_2022_12_20_220000_7002629.bak' WITH  FILE = 1,  MOVE N'distributor1' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\StaySourced.mdf',  MOVE N'distributor1_log' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\StaySourced_log.ldf',  NOUNLOAD,  STATS = 5
RESTORE DATABASE [TemplateDB30-8-2016] FROM  DISK = N'D:\Martin1\TemplateDB30-8-2016_backup_2022_12_20_220000_7002629.bak' WITH  FILE = 1,  MOVE N'distributor1' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\TemplateDB30-8-2016.mdf',  MOVE N'distributor1_log' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\TemplateDB30-8-2016_log.ldf',  NOUNLOAD,  STATS = 5
RESTORE DATABASE [TemplateDB] FROM  DISK = N'D:\Martin1\TemplateDB_backup_2022_12_20_220000_7002629.bak' WITH  FILE = 1,  MOVE N'distributor1' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\TemplateDB.mdf',  MOVE N'distributor1_log' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\TemplateDB_log.ldf',  NOUNLOAD,  STATS = 5
RESTORE DATABASE [Testdb] FROM  DISK = N'D:\Martin1\Testdb_backup_2022_12_20_220000_7002629.bak' WITH  FILE = 1,  MOVE N'distributor1' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Testdb.mdf',  MOVE N'distributor1_log' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Testdb_log.ldf',  NOUNLOAD,  STATS = 5
RESTORE DATABASE [TestDistributor] FROM  DISK = N'D:\Martin1\TestDistributor_backup_2022_12_20_220000_7002629.bak' WITH  FILE = 1,  MOVE N'distributor1' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\TestDistributor.mdf',  MOVE N'distributor1_log' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\TestDistributor_log.ldf',  NOUNLOAD,  STATS = 5
RESTORE DATABASE [Test] FROM  DISK = N'D:\Martin1\Test_backup_2022_12_20_220000_7002629.bak' WITH  FILE = 1,  MOVE N'distributor1' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Test.mdf',  MOVE N'distributor1_log' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Test_log.ldf',  NOUNLOAD,  STATS = 5
RESTORE DATABASE [ThePromotionalFolio] FROM  DISK = N'D:\Martin1\ThePromotionalFolio_backup_2022_12_20_220000_7002629.bak' WITH  FILE = 1,  MOVE N'distributor1' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\ThePromotionalFolio.mdf',  MOVE N'distributor1_log' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\ThePromotionalFolio_log.ldf',  NOUNLOAD,  STATS = 5
RESTORE DATABASE [ThePromotionalWorks] FROM  DISK = N'D:\Martin1\ThePromotionalWorks_backup_2022_12_20_220000_7158895.bak' WITH  FILE = 1,  MOVE N'distributor1' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\ThePromotionalWorks.mdf',  MOVE N'distributor1_log' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\ThePromotionalWorks_log.ldf',  NOUNLOAD,  STATS = 5
RESTORE DATABASE [ThePromotionGroup] FROM  DISK = N'D:\Martin1\ThePromotionGroup_backup_2022_12_20_220000_7158895.bak' WITH  FILE = 1,  MOVE N'distributor1' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\ThePromotionGroup.mdf',  MOVE N'distributor1_log' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\ThePromotionGroup_log.ldf',  NOUNLOAD,  STATS = 5
RESTORE DATABASE [TheSourcingTeam] FROM  DISK = N'D:\Martin1\TheSourcingTeam_backup_2022_12_20_220000_7158895.bak' WITH  FILE = 1,  MOVE N'distributor1' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\TheSourcingTeam.mdf',  MOVE N'distributor1_log' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\TheSourcingTeam_log.ldf',  NOUNLOAD,  STATS = 5
RESTORE DATABASE [Transworld] FROM  DISK = N'D:\Martin1\Transworld_backup_2022_12_20_220000_7158895.bak' WITH  FILE = 1,  MOVE N'distributor1' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Transworld.mdf',  MOVE N'distributor1_log' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Transworld_log.ldf',  NOUNLOAD,  STATS = 5
RESTORE DATABASE [TwelveTenPromotions] FROM  DISK = N'D:\Martin1\TwelveTenPromotions_backup_2022_12_20_220000_7158895.bak' WITH  FILE = 1,  MOVE N'distributor1' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\TwelveTenPromotions.mdf',  MOVE N'distributor1_log' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\TwelveTenPromotions_log.ldf',  NOUNLOAD,  STATS = 5
RESTORE DATABASE [WahootiLondon] FROM  DISK = N'D:\Martin1\WahootiLondon_backup_2022_12_20_220000_7158895.bak' WITH  FILE = 1,  MOVE N'distributor1' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\WahootiLondon.mdf',  MOVE N'distributor1_log' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\WahootiLondon_log.ldf',  NOUNLOAD,  STATS = 5
RESTORE DATABASE [WillsmerWaggLimited] FROM  DISK = N'D:\Martin1\WillsmerWaggLimited_backup_2022_12_20_220000_7158895.bak' WITH  FILE = 1,  MOVE N'distributor1' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\WillsmerWaggLimited.mdf',  MOVE N'distributor1_log' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\WillsmerWaggLimited_log.ldf',  NOUNLOAD,  STATS = 5
RESTORE DATABASE [Zagwear] FROM  DISK = N'D:\Martin1\Zagwear_backup_2022_12_20_220000_7315158.bak' WITH  FILE = 1,  MOVE N'distributor1' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Zagwear.mdf',  MOVE N'distributor1_log' TO N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\Zagwear_log.ldf',  NOUNLOAD,  STATS = 5

GO


